### ISSUE TITLE
Install instruction in VsCode plugin

### ISSUE THREAD

**Issue by jnarboux** [impermeable/coq-waterproof#39]
Hi,

The installation instructions displayed in the VSCode plugin does not seem to be correct.
opam install coq-lsp -v 8.17
opam: PACKAGES... arguments: Invalid character in package name "8.17"

Then I installed coq.8.17.0, then I get:

opam install  coq-waterproof
Sorry, no solution found: there seems to be a problem with your request.

**Comment by jnarboux** [comment]
opam install coq-lsp.0.1.8+8.17 works but opam install coq-waterproof fails because of the contraint on ocaml compiler.

Then I did:

opam switch create ocaml-base-compiler.4.14.1
opam install coq-waterproof

It works.

**Comment by jim-portegies** [comment]
The constraint on the ocaml compiler was relaxed with PR #45
